sqlserver.url=jdbc:sqlserver://localhost:1433;databaseName=MediTechDB;encrypt=true;trustServerCertificate=true

sqlserver.user=sa
#Cambiar 'sa' por el usuario

sqlserver.password=TU_PASSWORD
#Al igual que 'TU_PASSWORD' por la brindada para el usuario


# PostgreSQL

postgres.url=jdbc:postgresql://localhost:5432/meditechdb
postgres.user=postgres
postgres.password=TU_PASSWORD
#Lo mismo aplica para estas bases, cambiar clave y usuario a corde


# MariaDB

mariadb.url=jdbc:mariadb://localhost:3308/meditechdb
mariadb.user=root
mariadb.password=root
#Si