sqlserver.url=jdbc:sqlserver://localhost:1433;databaseName=meditech;encrypt=true;trustServerCertificate=true

sqlserver.user=sa

sqlserver.password=2122


# PostgreSQL

postgres.url=jdbc:postgresql://localhost:5432/meditech
postgres.user=postgres
postgres.password=2122


# MariaDB

mariadb.url=jdbc:mariadb://localhost:3308/meditech
mariadb.user=root
mariadb.password=root